#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/novodoc-remote/novodoc-remote /usr/bin/novodoc-remote

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/novodoc-remote.service ]; then
			rm /etc/systemd/system/novodoc-remote.service /usr/lib/systemd/system/novodoc-remote.service /usr/lib/systemd/user/novodoc-remote.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/novodoc-remote/files/systemd/novodoc-remote.service /usr/lib/systemd/system/novodoc-remote.service
		# try fix error in Ubuntu 18.04
		# Failed to reload novodoc-remote.service: Unit novodoc-remote.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/novodoc-remote.service:10: Executable path is not absolute: pkill -f "novodoc-remote --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/novodoc-remote.service
		fi
		systemctl daemon-reload
		systemctl enable novodoc-remote
		systemctl start novodoc-remote
	fi
fi
